### PR TITLE
Fix for PEP8

### PR DESCRIPTION
**Pull request by sinhrks**

### CODE REVIEW

**Comment by scls19fr** [comment]
We might add

    - flake8 --version

in `.travis.yml`
before

  - flake8 --ignore E501 pandas_ml

to be able to test locally PEP8 with same tool version

**Comment by sinhrks** [comment]
Yeah, but I think it's ok to use latest as it easy to fix.

**Comment by sinhrks** [comment]
Merging, reconsider to fix ``pyflake8`` version if its ver-up causes a problem again.

**Comment by scls19fr** [comment]
Idea here wasn't to change pyflake8 version... just to display in Travis build which version is being used.

**Pull request merged**
